[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
[dependencies]
actix-web = {git = "https://github.com/actix/actix-web"}
log = "0.4.0"
env_logger = "0.5.10"


