[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
[dependencies]
actix-web = {git = "https://github.com/actix/actix-web"}
log = "0.4.0"
env_logger = "0.5.10"
serde_json = "1.0"
serde = "1.0.70"
serde_derive = "1.0.70"
rand="0.5.3"
bytes="0.4.8"
byteorder="1.2.3"
futures="0.1.21"
tokio-core="0.1.17"
tokio-io="0.1.7"