[package]
name = "websocket"
version = "0.1.0"
authors = ["Alberto Cole <acpii2005@gmail.com>"]
[dependencies]
actix-web = "0.7.3"
log = "0.4.3"
env_logger = "0.5.12"
serde_json = "1.0.24"
serde = "1.0.71"
serde_derive = "1.0.71"
rand="0.5.4"
bytes="0.4.9"
byteorder="1.2.4"
futures="0.1.23"
tokio-core="0.1.17"
tokio-io="0.1.7"